from nflsim.inits.stats import stats
from nflsim.inits.stats import defense
from nflsim.inits.stats import kicking
from nflsim.inits.stats import passing
from nflsim.inits.stats import punting
from nflsim.inits.stats import receiving
from nflsim.inits.stats import returning
from nflsim.inits.stats import rushing
from nflsim.inits.stats import scoring
from nflsim.inits.stats import stats_init
