class COLS:
    class SCHEDULES:
        GSIS = "gsis"
        SEASON = "season"
        WEEK = "week"
        GAME_TYPE = "game_type"
        GAMEDAY = "gameday"
        WEEKDAY = "weekday"
        GAMETIME = "gametime"
        HOME_TEAM = "home_team"
        AWAY_TEAM = "away_team"
        HOME_REST = "home_rest"
        AWAY_REST = "away_rest"
        LOCATION = "location"

    class ROSTERS:
        SEASON = "season"
        TEAM = "team"
        POSITION = "position"
        DEPTH_CHART_POSITION = "depth_chart_position"
        JERSEY_NUMBER = "jersey_number"
        STATUS = "status"
        PLAYER_NAME = "player_name"
        FIRST_NAME = "first_name"
        LAST_NAME = "last_name"
        BIRTH_DATE = "birth_date"
        HEIGHT = "height"
        WEIGHT = "weight"
        COLLEGE = "college"
        PLAYER_ID = "player_id"
        ESPN_ID = "espn_id"
        SPORTRADAR_ID = "sportradar_id"
        YAHOO_ID = "yahoo_id"
        ROTOWIRE_ID = "rotowire_id"
        PFF_ID = "pff_id"
        PFR_ID = "pfr_id"
        FANTASY_DATA_ID = "fantasy_data_id"
        SLEEPER_ID = "sleeper_id"
        YEARS_EXP = "years_exp"
        HEADSHOT_URL = "headshot_url"
        NGS_POSITION = "ngs_position"
        WEEK = "week"
        GAME_TYPE = "game_type"
        STATUS_DESCRIPTION_ABBR = "status_description_abbr"
        FOOTBALL_NAME = "football_name"
        ESB_ID = "esb_id"
        GSIS_IT_ID = "gsis_it_id"
        SMART_ID = "smart_id"
        ENTRY_YEAR = "entry_year"
        ROOKIE_YEAR = "rookie_year"
        DRAFT_CLUB = "draft_club"
        DRAFT_NUMBER = "draft_number"
        AGE = "age"

    class TEAMS:
        ABBR = "team_abbr"
        NAME = "team_name"
        ID = "team_id"
        CONF = "team_conf"
        DIVISION = "team_division"

    class DRAFTS:
        SEASON = "season"
        ROUND = "round"
        PICK = "pick"
        TEAM = "team"
        GSIS_ID = "gsis_id"
        PFR_PLAYER_ID = "pfr_player_id"
        CFB_PLAYER_ID = "cfb_player_id"
        PFR_PLAYER_NAME = "pfr_player_name"
        HOF = "hof"
        POSITION = "position"
        CATEGORY = "category"
        SIDE = "side"
        COLLEGE = "college"
        AGE = "age"
        TO = "to"
        ALLPRO = "allpro"
        PROBOWLS = "probowls"
        SEASONS_STARTED = "seasons_started"
        W_AV = "w_av"
        CAR_AV = "car_av"
        DR_AV = "dr_av"
        GAMES = "games"
        PASS_COMPLETIONS = "pass_completions"
        PASS_ATTEMPTS = "pass_attempts"
        PASS_YARDS = "pass_yards"
        PASS_TDS = "pass_tds"
        PASS_INTS = "pass_ints"
        RUSH_ATTS = "rush_atts"
        RUSH_YARDS = "rush_yards"
        RUSH_TDS = "rush_tds"
        RECEPTIONS = "receptions"
        REC_YARDS = "rec_yards"
        REC_TDS = "rec_tds"
        DEF_SOLO_TACKLES = "def_solo_tackles"
        DEF_INTS = "def_ints"
        DEF_SACKS = "def_sacks"

    class STANDINGS:
        NFL_TEAM = "NFL Team"
        W = "W"
        L = "L"
        T = "T"
        PCT = "PCT"
        PF = "PF"
        PA = "PA"
        NET_PTS = "Net Pts"
        HOME = "Home"
        AWAY = "Away"
        DIV = "Div"
        CONF = "Conf"
        NON_CONF = "Non-Conf"
        STRK = "Strk"

    class STAT_CATEGORIES:
        PASSING = "Passing"
        RUSHING = "Rushing"
        RECEIVING = "Receiving"
        DEFENSE = "Defense"
        SCORING = "Scoring"
        RETURNING = "Returning"
        KICKING = "Kicking"
        PUNTING = "Punting"

    class STAT_PASSING:
        GP = "GP"
        CMP = "CMP"
        ATT = "ATT"
        CMPP = "CMP%"
        YDS = "YDS"
        AVG = "AVG"
        TD = "TD"
        INT = "INT"
        LNG = "LNG"
        SACK = "SACK"

    class STAT_RUSHING:
        GP = "GP"
        CAR = "CAR"
        YDS = "YDS"
        AVG = "AVG"
        TD = "TD"
        LNG = "LNG"
        FD = "FD"
        FUM = "FUM"
        LST = "LST"

    class STAT_RECEIVING:
        GP = "GP"
        REC = "REC"
        TGTS = "TGTS"
        YDS = "YDS"
        AVG = "AVG"
        TD = "TD"
        LNG = "LNG"
        FD = "FD"
        FUM = "FUM"
        LST = "LST"

    class STAT_DEFENSE:
        GP = "GP"
        TOT = "TOT"
        SOLO = "SOLO"
        AST = "AST"
        SACK = "SACK"
        FF = "FF"
        FR = "FR"
        FYDS = "FYDS"
        INT = "INT"
        IYDS = "IYDS"
        AVG = "AVG"
        TD = "TD"
        LNG = "LNG"
        PD = "PD"
        STF = "STF"
        STFYDS = "STFYDS"
        KB = "KB"

    class STAT_SCORING:
        GP = "GP"
        PASS = "PASS"
        RUSH = "RUSH"
        REC = "REC"
        RET = "RET"
        TD = "TD"
        TWOPT = "2PT"
        PAT = "PAT"
        FG = "FG"
        PTS = "PTS"

    class STAT_RETURNING:
        GP = "GP"
        PATT = "PATT"
        PYDS = "PYDS"
        PTD = "PTD"
        PFC = "PFC"
        PLNG = "PLNG"
        KATT = "KATT"
        KYDS = "KYDS"
        KTD = "KTD"
        KRFC = "KRFC"
        KLNG = "KLNG"

    class STAT_KICKING:
        GP = "GP"
        FG = "FG"
        FGP = "FG%"
        Y01_19 = "1-19"
        Y20_29 = "20-29"
        Y30_39 = "30-39"
        Y40_49 = "40-49"
        Y50P = "50+"
        LNG = "LNG"
        XPM = "XPM"
        XPA = "XPA"
        PTS = "PTS"

    class STAT_PUNTING:
        GP = "GP"
        PUNTS = "PUNTS"
        AVG = "AVG"
        LNG = "LNG"
        YDS = "YDS"
        TB = "TB"
        TBP = "TB%"
        IN20 = "IN20"
        IN20P = "IN20%"
        ATT = "ATT"
        RYDS = "RYDS"
        RAVG = "RAVG"
        NET = "NET"
